### ISSUE TITLE
[BUG] Filter `| where 1=1.0` returns false 

### ISSUE THREAD

**Issue by LantaoJin** [opensearch-project/opensearch-spark#503] opened 2024-08-01 07:20 UTC
Filter `| where 1=1.0` return false incorrectly.

**Comment by LantaoJin** [comment] 2024-08-01 07:58
```java
  test("create ppl simple age literal equal filter query with two fields result test1") {
    val frame = sql(
      s"""
         | source = $testTable age=25 and 25=25.0 | fields name, age
         | """.stripMargin)

    // Retrieve the results
    val results: Array[Row] = frame.collect()
    // Define the expected results
    val expectedResults: Array[Row] = Array(Row("John", 25))
    // Compare the results
    implicit val rowOrdering: Ordering[Row] = Ordering.by[Row, String](_.getAs[String](0))
    assert(results.sorted.sameElements(expectedResults.sorted))
  }
```

**Comment by kt-eliatra** [comment] 2024-08-20 11:32
@salyh @YANG-DB 

Hi, I cannot reproduce this problem, test mentioned [above](https://github.com/opensearch-project/opensearch-spark/issues/503#issuecomment-2262297936) [passes](https://github.com/eliatra/opensearch-spark/actions/runs/10469685330/job/28993253324) (tested on the main branch).
Most likely [these changes](https://github.com/eliatra/opensearch-spark/commit/1f81ddf88ac96cd0130c9bd8f32abc4454e90699#diff-723df1152f350a1aad0ae7428008473575a9708409dc2d16dc0a29916b25824dR54-R63) fixed the issue?

**Comment by YANG-DB** [comment] 2024-08-20 14:42
Thanks again for checking this out - I will close the issues...

**Closed** 2024-08-20 18:23 UTC
Labels: bug, PPL
