### ISSUE TITLE
[BUG] Streaming job does exist even the query has syntax error

### ISSUE THREAD

**Issue by penghuo** [opensearch-project/opensearch-spark#116] opened 2023-10-30 23:53 UTC
* failed query
```
CREATE INDEX mys3_default_http_logs ON mys3.default.http_logs (status) WITH (auto_refresh = true),query_execution_result_mys3
```

* error log
```
23/10/30 23:44:56 ERROR FlintJob: Fail to write result, cause: Checkpoint location is mandatory for incremental refresh if spark.flint.index.checkpoint.mandatory enabled
java.lang.IllegalStateException: Checkpoint location is mandatory for incremental refresh if spark.flint.index.checkpoint.mandatory enabled
```

**Comment by dai-chen** [comment] 2023-11-14 22:20
Investigated with @kaituo and found root cause maybe https://github.com/opensearch-project/opensearch-spark/blob/main/spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJob.scala#L87

Currently no matter if streaming job created or not (syntax/semantic error when creating), we let main thread wait for any streaming job termination. This may cause main thread wait forever.

**Comment by kaituo** [comment] 2023-11-16 04:03
resolved in above PR

**Closed by kaituo** 2023-11-16 04:03 UTC
Labels: bug, 0.1.1
